### ISSUE TITLE
有两个链接失效了，能帮忙修正一下么？

### ISSUE THREAD

**Issue by IguoChan** [cyub/grpc-examples#1]
![image](https://github.com/cyub/grpc-examples/assets/49904799/a1465e63-b1dd-4c67-a679-be9cc600add1)
这上面的两个链接失效了，能帮忙补充下么？另外，这个 192168.33.10 是什么ip啊，我本地是kind搭建的k8s环境，有点对不上。

**Comment by cyub** [comment]
README里面的是v1.20版本API地址，看来起失效了。官方目前v1.26版本API。https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#endpoints-v1-core
192.168.33.10是我ubuntu虚拟机IP，我是在虚拟机里面的部署docker的，然后本地电脑33.10访问他们。你本地部署可以直接访问127.0.0.1
